CREATE DATABASE DB_ESTOQUE;
GO

USE DB_ESTOQUE;
GO

CREATE TABLE ESTOQUE(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	SKU VARCHAR(20) UNIQUE NOT NULL,
	QUANTIDADE INT NOT NULL
);
GO

INSERT INTO ESTOQUE (SKU, QUANTIDADE) VALUES ('CELNVIPHONE12', 100);
GO