CREATE DATABASE DB_CLIENTES;
GO

USE DB_CLIENTES;
GO

CREATE TABLE CLIENTES(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(50) UNIQUE NOT NULL
);
GO

INSERT INTO CLIENTES (NOME, EMAIL) VALUES ('FELIPE TOSCANO', 'FELIPETOSCANO02@GMAIL.COM');
GO